name: Run Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  changed-files:
    name: Changed Files
    runs-on: ubuntu-latest
    outputs:
      rust: ${{ steps.changed-files.outputs.rust_any_modified == 'true' }}
      docker-build: ${{ steps.changed-files.outputs.docker-build_any_modified == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits

      - name: Find changed files
        uses: tj-actions/changed-files@v46
        id: changed-files
        with:
          files_yaml: |
            common: &common
              - .github/workflows/test-worker.yml
              - Makefile

            rust: &rust
              - *common
              - src/**
              - Cargo.toml
              - Cargo.lock

            docker-build:
              - *common
              - *rust
              - Dockerfile

  rust:
    name: "Rust"
    runs-on: ubuntu-latest
    needs: [changed-files]
    if: needs.changed-files.outputs.rust == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Caching dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: rust-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml', '**/Cargo.lock') }}
          restore-keys: |
            rust-${{ runner.os }}

      - name: Setup Rust
        run: |
          rustup show active-toolchain || (rustup update)

      - name: Install tooling
        run: |
          make install

      - name: Linting
        run: |
          make lint/check

      - name: Formatting
        run: |
          make fmt/check

      - name: Run tests
        run: |
          make test

  docker:
    name: "Docker"
    runs-on: ubuntu-latest
    needs: [changed-files]
    if: needs.changed-files.outputs.docker-build == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=registry,ref=ghcr.io/caffeine-addictt/audiopatch:buildcache
          cache-to: type=registry,ref=ghcr.io/caffeine-addictt/audiopatch:buildcache,mode=max
          push: true
          tags: ghcr.io/caffeine-addictt/audiopatch:latest
          labels: |
            org.opencontainers.image.source=https://github.com/caffeine-addictt

  check:
    if: always()
    name: Tests Successful
    runs-on: ubuntu-latest
    needs: [rust, docker]

    steps:
      - name: Whether the whole test suite passed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: ${{ toJSON(needs) }}
